---
title: "About Me"
---

I'm a Lecturer at the University of Maryland at College Park, in the College of Information (aka INFO). I teach [courses](course_links.qmd) related to building foundational skills in data science and related areas. I am also the Co-Director for the [undergraduate major in Social Data Science](https://sdsc.umd.edu/), which is an interdisciplinary, cross-college major that allows students to combine both technical skills and content area knowledge in one of nine tracks.

Here's a short run-down of my educational and professional career, which has had zome zigs and zags:

- BA in Linguistics and BMusic in Music Studies (Education) from the University of Texas at Austin
- PhD in Linguistics from the University of Arizona, with a minor in Neuroscience and a focus in psycholinguistics
- Postdoctoral Fellow at the University of Illinois, Urbana-Champaign, learning to use ERP brain imaging to explore human sentence processing, particularly related to prosody and intonation
- Research Scientist at the University of Maryland Center for Advanced Study of Language, focusing on assessing aptitude for language learning (as an adult)
- Data Scientist at a small cyber-adjacent startup company
- Full-time Lecturer at the University of Maryland since Fall of 2023

The common thread here is that I am passionate about *meaningful* data analysis, and that I love teaching and passing on skills to others.
